dogs = {'komondor', 'irish_terrier', 'briard', 'old_english_sheepdog', 'white_wolf', 'rottweiler', 'basenji',
        'staffordshire_bullterrier', 'australian_terrier', 'border_terrier', 'norfolk_terrier',
        'west_highland_white_terrier', 'flat-coated_retriever', 'greater_swiss_mountain_dog', 'basset',
        'tibetan_terrier', 'miniature_pinscher', 'irish_setter', 'norwich_terrier', 'silky_terrier', 'mexican_hairless',
        'walker_hound', 'pembroke', 'scottish_deerhound', 'entlebucher', 'yorkshire_terrier', 'dalmatian',
        'standard_poodle', 'malamute', 'boxer', 'tibetan_mastiff', 'blenheim_spaniel', 'toy_poodle', 'border_collie',
        'ibizan_hound', 'great_dane', 'saint_bernard', 'leonberg', 'kelpie', 'whippet', 'cairn', 'schipperke',
        'miniature_schnauzer', 'redbone', 'timber_wolf', 'kuvasz', 'brittany_spaniel', 'bluetick', 'english_foxhound',
        'english_springer', 'german_short-haired_pointer', 'siberian_husky', 'bloodhound', 'otterhound', 'shih-tzu',
        'scotch_terrier', 'great_pyrenees', 'italian_greyhound', 'pekinese', 'english_setter', 'samoyed',
        'wire-haired_fox_terrier', 'vizsla', 'lakeland_terrier', 'groenendael', 'bedlington_terrier', 'irish_wolfhound',
        'standard_schnauzer', 'cocker_spaniel', 'afghan_hound', 'doberman', 'chesapeake_bay_retriever',
        'labrador_retriever', 'soft-coated_wheaten_terrier', 'collie', 'toy_terrier', 'miniature_poodle',
        'brabancon_griffon', 'dandie_dinmont', 'welsh_springer_spaniel', 'appenzeller', 'golden_retriever', 'airedale',
        'eskimo_dog', 'boston_bull', 'french_bulldog', 'bouvier_des_flandres', 'lhasa', 'maltese_dog',
        'kerry_blue_terrier', 'pomeranian', 'pug', 'papillon', 'sealyham_terrier', 'newfoundland',
        'african_hunting_dog', 'american_staffordshire_terrier', 'shetland_sheepdog', 'cardigan', 'japanese_spaniel',
        'chow', 'chihuahua', 'keeshond', 'rhodesian_ridgeback', 'bull_mastiff', 'norwegian_elkhound', 'malinois',
        'clumber', 'dingo', 'weimaraner', 'black-and-tan_coonhound', 'saluki', 'coyote', 'affenpinscher',
        'sussex_spaniel', 'borzoi', 'german_shepherd', 'giant_schnauzer', 'curly-coated_retriever', 'red_wolf',
        'gordon_setter', 'irish_water_spaniel', 'beagle', 'dhole', 'bernese_mountain_dog'}
